<a href="https://colab.research.google.com/github/SakshyamSingB/AI-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4 TO-DO-**Task**

**4.1 Exercise on Functions:**


Task- 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L)

In [55]:
def convert_units(conversion_type, value):
    """
    Converts units based on the conversion type.

    Parameters:
    conversion_type (str): Type of conversion selected by the user.
    value (float): Numeric value to convert.

    Returns:
    float: Converted value.
    """

    if conversion_type == "1":  # meters to feet
        return value * 3.28084
    elif conversion_type == "2":  # feet to meters
        return value / 3.28084
    elif conversion_type == "3":  # kg to lbs
        return value * 2.20462
    elif conversion_type == "4":  # lbs to kg
        return value / 2.20462
    elif conversion_type == "5":  # liters to gallons
        return value * 0.264172
    elif conversion_type == "6":  # gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    choice = input("Choose conversion type (1-6): ")

    try:
        value = float(input("Enter value to convert: "))
        result = convert_units(choice, value)

        if result is not None:
            print("Converted value:", result)
        else:
            print("Invalid conversion type selected.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    main()

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 1
Enter value to convert: 3
Converted value: 9.84252


Task- 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value

In [56]:
def calculate_sum(numbers):
    """
    Returns the sum of numbers in the list.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Returns the average of numbers in the list.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Returns the maximum number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Returns the minimum number in the list.
    """
    return min(numbers)


def main():
    print("Mathematical Operations Program")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Choose operation (1-4): ")

    try:
        user_input = input("Enter numbers separated by spaces: ")
        numbers = list(map(float, user_input.split()))

        if not numbers:
            raise ValueError("Empty list")

        if choice == "1":
            print("Sum:", calculate_sum(numbers))
        elif choice == "2":
            print("Average:", calculate_average(numbers))
        elif choice == "3":
            print("Maximum:", find_maximum(numbers))
        elif choice == "4":
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid choice.")

    except ValueError:
        print("Error: Please enter valid numbers and ensure the list is not empty.")


if __name__ == "__main__":
    main()

Mathematical Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Choose operation (1-4): 1
Enter numbers separated by spaces: 1 3
Sum: 4.0


**4.2 Exercise on List Manipulation:**
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:– Define a function extract
every
other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5]

In [57]:
def extract_every_other(lst):
    return lst[::2]

In [58]:
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:– Define a function get
sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [59]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

In [60]:
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print("Original list:",numbers)
print("Sublist:",result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:– Define a function reverse
slicing.
list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [61]:
def reverse_list(lst):
    return lst[::-1]

In [62]:
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print("Original list:",numbers)
print("Reversed list:",result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:– Defineafunction remove
first
last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [63]:
def remove_first_last(lst):
    return lst[1:-1]

In [64]:
numbers = [1, 2, 3, 4, 5]

result = remove_first_last(numbers)

print("Original list:", numbers)
print("List after removing first and last elements:", result)

Original list: [1, 2, 3, 4, 5]
List after removing first and last elements: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:– Define a function get
first
n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [65]:
def get_first_n(lst, n):
    return lst[:n]

In [66]:
numbers = [1, 2, 3, 4, 5]
n = 3

result = get_first_n(numbers, n)

print("Original list:", numbers)
print(f"First {n} elements:", result)

Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:– Define a function get
last
n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5]

In [67]:
def get_last_n(lst, n):
    return lst[-n:]

In [68]:
numbers = [1, 2, 3, 4, 5]
n = 2

result = get_last_n(numbers, n)

print("Original list:", numbers)
print(f"Last {n} elements:", result)

Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:– Define a function reverse
skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [69]:
def reverse_skip(lst):
    return lst[-2::-2]

In [70]:
numbers = [1, 2, 3, 4, 5, 6]

result = reverse_skip(numbers)

print("Original list:", numbers)
print("Every second element in reverse starting from second-to-last:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every second element in reverse starting from second-to-last: [5, 3, 1]


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [71]:
def flatten(lst):
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

In [72]:
nested = [[1, 2], [3, 4], [5]]

result = flatten(nested)

print("Original nested list:", nested)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:– Define a function access
nested
element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [73]:
def access_nested_element(lst, indices):
    element = lst
    for idx in indices:
        element = element[idx]
    return element

In [74]:
nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(nested, indices)

print("Nested list:", nested)
print(f"Element at indices {indices}:", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:– Define a function sum
nested(lst) that takes a nested list lst and returns the sum of all
the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21

In [75]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # recursive call for nested list
        else:
            total += item
    return total

In [76]:
nested = [[1, 2], [3, [4, 5]], 6]

result = sum_nested(nested)

print("Nested list:", nested)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:– Define a function remove
element(lst, elem) that removes elem from lst and returns the
modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
be [[1], [3], [4, 5]].

In [77]:
def remove_element(lst, elem):
    new_list = []
    for sublist in lst:
        # Only process if the item is a list
        if isinstance(sublist, list):
            filtered = [x for x in sublist if x != elem]
            new_list.append(filtered)
        else:
            # If the top-level item is not a list, skip or remove if it matches elem
            if sublist != elem:
                new_list.append(sublist)
    return new_list

In [78]:
nested = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(nested, elem)

print("Original nested list:", nested)
print(f"Nested list after removing {elem}:", result)

Original nested list: [[1, 2], [3, 2], [4, 5]]
Nested list after removing 2: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:– Define a function find
element.
max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [79]:
def find_element_max(lst):
    max_val = float('-inf')  # Start with the smallest possible value
    for item in lst:
        if isinstance(item, list):
            # Recursively find max in nested list
            nested_max = find_element_max(item)
            if nested_max > max_val:
                max_val = nested_max
        else:
            if item > max_val:
                max_val = item
    return max_val

In [80]:
nested = [[1, 2], [3, [4, 5]], 6]

result = find_element_max(nested)

print("Nested list:", nested)
print("Maximum element:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:– Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
be 3

In [81]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recursively count in nested list
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

In [82]:
nested = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(nested, elem)

print("Nested list:", nested)
print(f"Occurrences of {elem}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:– Define a function deep
flatten(lst) that takes a deeply nested list lst and returns a single
f
lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [83]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursively flatten nested lists
        else:
            flat_list.append(item)
    return flat_list

In [84]:
nested = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

result = deep_flatten(nested)

print("Original deeply nested list:", nested)
print("Flattened list:", result)

Original deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:– Define a function average
of all the elements.
nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5

In [85]:
def average_nested(lst):
    def helper(sublist):
        total = 0
        count = 0
        for item in sublist:
            if isinstance(item, list):
                t, c = helper(item)  # recursively get sum and count
                total += t
                count += c
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = helper(lst)
    if total_count == 0:
        return 0  # Avoid division by zero
    return total_sum / total_count

In [86]:
nested = [[1, 2], [3, 4], [5, 6]]

result = average_nested(nested)

print("Nested list:", nested)
print("Average of all elements:", result)

Nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


**10 To- Do-** **NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**


Problem- 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [87]:
import numpy as np

In [88]:
#Initialize an empty array with size 2×2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

Empty 2x2 array:
 [[6.65800395e-310 1.78465634e-315]
 [4.94065646e-324             nan]]


In [89]:
#Initialize an all-one array with size 4×2
ones_array = np.ones((4, 2))
print("\nAll ones 4x2 array:\n", ones_array)


All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [90]:
#Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), fill_value=7)  # 3x3 array filled with 7
print("\nArray filled with 7:\n", fill_value_array)


Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [91]:
#Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros array like given array:\n", zeros_like_array)


Zeros array like given array:
 [[0 0]
 [0 0]]


In [92]:
#Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes array like given array:\n", ones_like_array)


Ones array like given array:
 [[1 1]
 [1 1]]


In [93]:
#Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nNumPy array from list:\n", array_from_list)


NumPy array from list:
 [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [94]:
#import numpy
import numpy as np

In [95]:
#Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr1)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [96]:
#Create a 3×3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape((3, 3))
print("\n3x3 matrix 0 to 8:\n", matrix_3x3)


3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [97]:
#Create a 3×3 identity matrix
identity_3x3 = np.eye(3)
print("\n3x3 Identity matrix:\n", identity_3x3)


3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
#Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_val = random_array_30.mean()
print("\nRandom array of size 30:\n", random_array_30)
print("Mean of the array:", mean_val)


Random array of size 30:
 [0.01797526 0.45006788 0.20546717 0.33330288 0.63997789 0.84508113
 0.03144417 0.90799399 0.49328573 0.21541897 0.43396759 0.83454545
 0.2861438  0.17086605 0.48023422 0.60257536 0.71898843 0.65690531
 0.34027719 0.39455234 0.01027523 0.88191176 0.75778413 0.36277029
 0.865326   0.32453116 0.66836488 0.13292901 0.38712225 0.45028794]
Mean of the array: 0.4633457818688956


In [99]:
#Create a 10×10 array with random values and find min & max
random_array_10x10 = np.random.random((10, 10))
min_val = random_array_10x10.min()
max_val = random_array_10x10.max()
print("\nRandom 10x10 array:\n", random_array_10x10)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


Random 10x10 array:
 [[5.46391838e-02 4.70906525e-01 6.20134481e-02 5.03792862e-01
  3.23026730e-01 5.98313100e-01 6.03361914e-01 6.34340056e-01
  7.98654290e-01 3.12546424e-01]
 [3.38318211e-01 4.11214748e-01 1.72542870e-01 2.94213835e-01
  2.64112022e-01 8.50508370e-02 6.12585919e-01 8.02396926e-01
  9.38492774e-01 8.02926417e-01]
 [9.26046367e-01 6.67721873e-01 5.02461852e-01 2.11458812e-01
  9.05732635e-01 7.34302569e-01 4.75726113e-01 3.21515585e-01
  5.46121738e-01 8.35632682e-02]
 [8.75416914e-01 8.88409792e-02 4.15203483e-01 2.29151488e-01
  9.46762536e-01 5.20511608e-01 1.24525940e-01 2.78581477e-01
  8.56653588e-01 1.40339299e-01]
 [9.63577844e-01 7.58233945e-01 1.99471054e-01 1.99197971e-01
  3.94084990e-01 5.19616797e-01 6.39307748e-01 3.86934324e-01
  3.97302662e-01 6.22843451e-02]
 [4.89214175e-01 7.48896118e-01 4.68663243e-01 4.99044610e-01
  2.65786913e-02 5.75284494e-01 2.18361646e-01 7.95808558e-01
  3.16123892e-02 3.47998205e-01]
 [2.96485314e-01 6.90678652e-01 2.51

In [100]:
#Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("\nZero array with 5th element as 1:\n", zero_array)


Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [101]:
#Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nOriginal array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1]


In [102]:
#Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)


2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [103]:
#Create an 8×8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


8x8 Checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem- 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [104]:
#define the arrays:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [105]:
#Add the two arrays x + y
add_xy = x + y
print("x + y:\n", add_xy)

x + y:
 [[ 6  8]
 [10 13]]


In [106]:
#Subtract the two arrays x - y
sub_xy = x - y
print("\nx - y:\n", sub_xy)


x - y:
 [[-4 -4]
 [-4 -3]]


In [107]:
#Multiply the array by an integer (e.g., 3)
mult_x = x * 3
print("\nx * 3:\n", mult_x)


x * 3:
 [[ 3  6]
 [ 9 15]]


In [108]:
# Square each element of the array
square_x = x ** 2
print("\nSquare of each element in x:\n", square_x)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [109]:
#Dot product

# a) Dot product v . w (vectors)
dot_vw = np.dot(v, w)
print("\nv . w =", dot_vw)


v . w = 219


In [110]:
# b) Dot product x . v (matrix and vector)
dot_xv = np.dot(x, v)
print("x . v =", dot_xv)

x . v = [29 77]


In [111]:
# c) Dot product x . y (matrix and matrix)
dot_xy = np.dot(x, y)
print("x . y =\n", dot_xy)

x . y =
 [[19 22]
 [50 58]]


In [112]:
#  Concatenate arrays

# a) Concatenate x and y along rows (vertical stacking)
concat_xy_rows = np.vstack((x, y))
print("\nConcatenate x and y along rows:\n", concat_xy_rows)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [113]:
# b) Concatenate v and w along columns (as 2D column vectors)
concat_vw_cols = np.column_stack((v, w))
print("\nConcatenate v and w along columns:\n", concat_vw_cols)


Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [114]:
#⃣⃣ ⃣ Try to concatenate x and v
try:
    concat_xv = np.concatenate((x, v))
except ValueError as e:
    print("\nError when concatenating x and v:", e)


Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem- 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB̸ = BA.
3. Prove (AB)T = BTAT.
• Solve the following system of Linear equation using Inverse Methods.
2x −3y+z =−1
x −y+2z =−3
3x +y−z =9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy

In [115]:
import numpy as np


In [116]:
# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [117]:
# To prove A.A−1 = I.
A_inv = np.linalg.inv(A)  # Inverse of A
I = np.dot(A, A_inv)      # Multiply A by its inverse

I_rounded = np.round(I, decimals=10)
print("A * A^-1 (rounded) =\n", I_rounded)

A * A^-1 (rounded) =
 [[1. 0.]
 [0. 1.]]


In [118]:
# To prove AB̸ = BA.
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nA * B =\n", AB)
print("B * A =\n", BA)
print("AB equal to BA?", np.array_equal(AB, BA))


A * B =
 [[23 13]
 [51 29]]
B * A =
 [[36 44]
 [13 16]]
AB equal to BA? False


In [119]:
#To prove (AB)T = BTAT
AB_T = (np.dot(A, B)).T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)
print("(AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))


(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T equal to B^T * A^T? True


**10.2 Experiment: How Fast is Numpy?**


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
and Print the time taken for this operation.


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation

In [120]:
# Import required modules
import numpy as np
import time

In [121]:
# 3 Create lists and arrays
# Size of the arrays/lists
N = 1_000_000

# Python lists
list1 = list(range(N))
list2 = list(range(N))

# NumPy arrays
array1 = np.arange(N)
array2 = np.arange(N)


In [122]:
#Element-wise addition using Python lists
start_time = time.time()

# Using list comprehension for element-wise addition
result_list = [list1[i] + list2[i] for i in range(N)]

end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists: 0.223813 seconds


In [123]:
#Element-wise addition using NumPy arrays
start_time = time.time()

# Using NumPy vectorized addition
result_array = array1 + array2

end_time = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time - start_time))

Time taken using NumPy arrays: 0.016850 seconds


NumPy is much faster than plain Python lists for large element-wise operations.

This is because NumPy uses vectorized C implementations internally, while Python lists perform operations element by element in Python, which is slower.

2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
Measure and Print the time taken for this operation.


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [124]:
#Create lists and arrays
N = 1_000_000

# Python lists
list1 = list(range(N))
list2 = list(range(N))

# NumPy arrays
array1 = np.arange(N)
array2 = np.arange(N)

In [125]:
# Element-wise multiplication using Python lists
start_time = time.time()

# List comprehension for element-wise multiplication
result_list = [list1[i] * list2[i] for i in range(N)]

end_time = time.time()
print("Time taken using Python lists (multiplication): {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists (multiplication): 0.232560 seconds


In [126]:
# Element-wise multiplication using NumPy arrays
start_time = time.time()

# NumPy vectorized multiplication
result_array = array1 * array2

end_time = time.time()
print("Time taken using NumPy arrays (multiplication): {:.6f} seconds".format(end_time - start_time))

Time taken using NumPy arrays (multiplication): 0.005486 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and

Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [127]:
# Create lists and arrays
N = 1_000_000

# Python lists
list1 = list(range(N))
list2 = list(range(N))

# NumPy arrays
array1 = np.arange(N)
array2 = np.arange(N)

In [128]:
# Dot product using Python lists
start_time = time.time()

# Using sum of element-wise multiplication
dot_list = sum(list1[i] * list2[i] for i in range(N))

end_time = time.time()
print("Time taken using Python lists (dot product): {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists (dot product): 0.208338 seconds


In [129]:
# Dot product using NumPy arrays
start_time = time.time()

# NumPy dot product
dot_array = np.dot(array1, array2)

end_time = time.time()
print("Time taken using NumPy arrays (dot product): {:.6f} seconds".format(end_time - start_time))

Time taken using NumPy arrays (dot product): 0.003068 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.
(Due to the matrix multiplication taking too long reduced it to 100)
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [133]:
# Create matrices
N = 100

# Python lists (nested lists)
list1 = [[i + j for j in range(N)] for i in range(N)]
list2 = [[i - j for j in range(N)] for i in range(N)]

# NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

In [134]:
# Matrix multiplication using Python lists
start_time = time.time()

# Initialize result matrix
result_list = [[0 for _ in range(N)] for _ in range(N)]

# Naive nested loop multiplication
for i in range(N):
    for j in range(N):
        for k in range(N):
            result_list[i][j] += list1[i][k] * list2[k][j]

end_time = time.time()
print("Time taken using Python lists (matrix multiplication): {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists (matrix multiplication): 0.278140 seconds


In [135]:
#Matrix multiplication using NumPy arrays
start_time = time.time()

# NumPy matrix multiplication (vectorized)
result_array = np.dot(array1, array2)

end_time = time.time()
print("Time taken using NumPy arrays (matrix multiplication): {:.6f} seconds".format(end_time - start_time))

Time taken using NumPy arrays (matrix multiplication): 0.001838 seconds
